---
- name: restart sshd
  service:
    name: "{{ 'sshd' if ansible_os_family == 'RedHat' else 'ssh' }}"
    state: restarted

- name: apply netplan
  command: netplan apply

- name: restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
