---
- name: Update package cache (apt)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_pkg_mgr == 'apt'

- name: Update package cache (dnf)
  dnf:
    update_cache: yes
  when: ansible_pkg_mgr == 'dnf'

- name: Install base packages
  package:
    name: "{{ base_packages }}"
    state: present
