---
fields:
  - name: linux_init_zsh
    label: 安装 oh-my-zsh
    type: bool
    required: true
    default: true
    placeholder: "安装 zsh"

  - name: zsh_theme
    label: Zsh 主题
    type: text
    depends_on: linux_init_zsh
    required: true
    default: bira

  - name: zsh_plugins
    label: Zsh 插件
    type: select
    depends_on: linux_init_zsh
    required: false
    default: ""
    option:
      - git
      - zsh-autosuggestions
      - zsh-syntax-highlighting
